### ISSUE TITLE
Should not throw NullPointerException when initializing tab

### ISSUE THREAD

**Issue by rsgoncalves** [NJITSABOC/oaf-protege#1]
Using Protege 5.2.0 on macOS 10.12.5, and oaf-1.0.0-beta, I get a NullPointerException when initializing tabs (see full stack trace at the bottom). To replicate:
* Install oaf plugin and open Protege
* Activate OAF or OAF Class Browser tab from Window > Tabs
* Open tab, and the result is as the screenshot below.

This happens without loading a specific ontology, as well as after loading an ontology.

<img width="1408" alt="screen shot 2017-06-04 at 17 18 36" src="https://cloud.githubusercontent.com/assets/4361140/26766597/f027db68-4949-11e7-825e-0766afd30b9f.png">

    2017-06-04 16:15:51.048 [AWT-EventQueue-0] ERROR View    An error occurred whilst creating the view content for the 'Ontology Abstraction Framework (OAF) Class Browser' view: {}
    java.lang.NullPointerException: null
    	at edu.njit.cs.saboc.blu.core.utils.toolstate.OAFRecentlyOpenedFileManager.ensureInitialized(OAFRecentlyOpenedFileManager.java:66) ~[na:na]
    	at edu.njit.cs.saboc.blu.core.utils.toolstate.OAFRecentlyOpenedFileManager.<init>(OAFRecentlyOpenedFileManager.java:43) ~[na:na]
    	at edu.njit.cs.saboc.blu.core.utils.toolstate.OAFRecentlyOpenedFileManager.<init>(OAFRecentlyOpenedFileManager.java:59) ~[na:na]
    	at edu.njit.cs.saboc.blu.core.utils.toolstate.OAFStateFileManager.<init>(OAFStateFileManager.java:30) ~[na:na]
    	at edu.njit.cs.saboc.blu.owl.protege.OAFProtegeNAT.initialiseOWLView(OAFProtegeNAT.java:114) ~[na:na]
    	at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:43) ~[na:na]
    	at org.protege.editor.core.ui.view.View.createContent(View.java:413) [protege-editor-core.jar:na]
    	at org.protege.editor.core.ui.view.View.createUI(View.java:220) [protege-editor-core.jar:na]
    	at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:124) [protege-editor-core.jar:na]
    	at java.awt.Component.processHierarchyEvent(Component.java:6692) [na:1.8.0_40]
    	at java.awt.Component.processEvent(Component.java:6311) [na:1.8.0_40]
    	at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
    	at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
    	at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
    	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
    	at java.awt.Component.createHierarchyEvents(Component.java:5541) [na:1.8.0_40]
    	at java.awt.Container.createHierarchyEvents(Container.java:1443) [na:1.8.0_40]
    	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
    	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
    	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
    	at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
    	at java.awt.Component.show(Component.java:1622) [na:1.8.0_40]
    	at java.awt.Component.show(Component.java:1654) [na:1.8.0_40]
    	at java.awt.Component.setVisible(Component.java:1606) [na:1.8.0_40]
    	at javax.swing.JComponent.setVisible(JComponent.java:2644) [na:1.8.0_40]
    	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) [na:1.8.0_40]
    	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) [na:1.8.0_40]
    	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) [na:1.8.0_40]
    	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) [na:1.8.0_40]
    	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) [na:1.8.0_40]
    	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) [na:1.8.0_40]
    	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) [na:1.8.0_40]
    	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) [na:1.8.0_40]
    	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) [na:1.8.0_40]
    	at java.awt.Component.processMouseEvent(Component.java:6522) [na:1.8.0_40]
    	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_40]
    	at java.awt.Component.processEvent(Component.java:6290) [na:1.8.0_40]
    	at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
    	at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
    	at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
    	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
    	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) [na:1.8.0_40]
    	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530) [na:1.8.0_40]
    	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) [na:1.8.0_40]
    	at java.awt.Container.dispatchEventImpl(Container.java:2278) [na:1.8.0_40]
    	at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_40]
    	at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
    	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) [na:1.8.0_40]
    	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
    	at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
    	at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
    	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
    	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_40]
    	at java.awt.EventQueue$4.run(EventQueue.java:724) [na:1.8.0_40]
    	at java.awt.EventQueue$4.run(EventQueue.java:722) [na:1.8.0_40]
    	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
    	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
    	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) [na:1.8.0_40]
    	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
    	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
    	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
    	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
    	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]

**Comment by ChrisOchs** [comment]
Fixed in latest build. Additional error check added. Config file manager refactored to better support ontologies that have not yet been saved to a file in OAF protege.
